# Exploring Data Foundation

## Demonstrating Issues and Problems on Data Quality (Group 4)
Using [Bike Sales Data](https://www.kaggle.com/datasets/ratnarohith/uncleaned-bike-sales-data)

## Data Loading and Initial Exploration

In [1]:
!pip install -r requirements.txt

Requirement already satisfied: pandas in c:\users\user\miniconda3\envs\qriente\lib\site-packages (from -r requirements.txt (line 1)) (2.2.3)
Requirement already satisfied: openpyxl in c:\users\user\miniconda3\envs\qriente\lib\site-packages (from -r requirements.txt (line 2)) (3.1.5)
Requirement already satisfied: numpy in c:\users\user\miniconda3\envs\qriente\lib\site-packages (from -r requirements.txt (line 3)) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\miniconda3\envs\qriente\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\miniconda3\envs\qriente\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\miniconda3\envs\qriente\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2024.2)
Requirement already satisfied: et-xmlfile in c:\users\user\miniconda3\envs\qriente\lib\site-packages (from openpyxl->-r requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\user\miniconda3\envs\qriente\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.17.0)

In [2]:
import pandas as pd

df = pd.read_excel("datasets/uncleaned bike sales data.xlsx")

In [3]:
df.head()

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,2021-12-01,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,1252,2295,4172,5008,9180
1,261695,2021-12-01,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,1266,2320,1054,1266,2320
2,261697,2021-12-02,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,420,769,698,840,1538
3,261698,2021-12-02,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,420,769,349,420,769
4,261699,2021-12-03,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,0,2295,2086,0,4590

In [4]:
df.describe()

,Sales_Order #,Date,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,89.000000,89,88.000000,89.0,89.000000,88.000000,89.000000,89.000000,89.000000,89.000000,89.00000
mean,261738.067416,2021-12-13 10:31:00.674157312,13.534091,2021.0,34.202247,2.125000,1052.247191,1940.943820,1848.887640,2204.235955,4043.94382
min,261695.000000,2021-12-01 00:00:00,1.000000,2021.0,17.000000,1.000000,0.000000,0.000000,245.000000,0.000000,0.00000
25%,261716.000000,2021-12-08 00:00:00,8.750000,2021.0,30.000000,1.000000,420.000000,2295.000000,1043.000000,1252.000000,2295.00000
50%,261738.000000,2021-12-13 00:00:00,13.500000,2021.0,35.000000,2.000000,1252.000000,2295.000000,1054.000000,1266.000000,2320.00000
75%,261760.000000,2021-12-19 00:00:00,19.000000,2021.0,38.000000,3.000000,1266.000000,2320.000000,2954.000000,3756.000000,6750.00000
max,261782.000000,2021-12-24 00:00:00,24.000000,2021.0,63.000000,4.000000,1912.000000,3400.000000,5908.000000,7592.000000,13500.00000
std,25.729713,NaN,6.391353,0.0,8.090651,1.239322,440.499001,789.955743,1394.401162,1730.330926,3139.75858

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sales_Order #        89 non-null     int64
 1   Date                 89 non-null     datetime64[ns]
 2   Day                  88 non-null     float64
 3   Month                89 non-null     object
 4   Year                 89 non-null     int64
 5   Customer_Age         89 non-null     int64
 6   Age_Group            88 non-null     object
 7   Customer_Gender      89 non-null     object
 8   Country              89 non-null     object
 9   State                89 non-null     object
 10  Product_Category     89 non-null     object
 11  Sub_Category         89 non-null     object
 12  Product_Description  88 non-null     object
 13  Order_Quantity       88 non-null     float64
 14   Unit_Cost           89 non-null     int64
 15   Unit_Price          89 non-null     int64
 16   Profit              89 non-null     int64
 17   Cost                89 non-null     int64
 18  Revenue              89 non-null     int64
dtypes: datetime64[ns](1), float64(2), int64(8), object(8)
memory usage: 13.3+ KB

In [6]:
df.isna().sum()

Sales_Order #          0
Date                   0
Day                    1
Month                  0
Year                   0
Customer_Age           0
Age_Group              1
Customer_Gender        0
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    1
Order_Quantity         1
 Unit_Cost             0
 Unit_Price            0
 Profit                0
 Cost                  0
Revenue                0
dtype: int64

## Data Cleaning using `dropna()`

In [7]:
sample_df = df.copy()

In [8]:
sample_df.isna().sum()

Sales_Order #          0
Date                   0
Day                    1
Month                  0
Year                   0
Customer_Age           0
Age_Group              1
Customer_Gender        0
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    1
Order_Quantity         1
 Unit_Cost             0
 Unit_Price            0
 Profit                0
 Cost                  0
Revenue                0
dtype: int64

In [9]:
sample_df.dropna(inplace=True)

In [10]:
sample_df.isna().sum()

Sales_Order #          0
Date                   0
Day                    0
Month                  0
Year                   0
Customer_Age           0
Age_Group              0
Customer_Gender        0
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    0
Order_Quantity         0
 Unit_Cost             0
 Unit_Price            0
 Profit                0
 Cost                  0
Revenue                0
dtype: int64

## Data Cleaning using `fillna()`

In [11]:
sample_df = df.copy()

In [12]:
sample_df.isna().sum()

Sales_Order #          0
Date                   0
Day                    1
Month                  0
Year                   0
Customer_Age           0
Age_Group              1
Customer_Gender        0
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    1
Order_Quantity         1
 Unit_Cost             0
 Unit_Price            0
 Profit                0
 Cost                  0
Revenue                0
dtype: int64

In [13]:
sample_df.fillna(method="ffill", inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_9132\1754511624.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sample_df.fillna(method="ffill", inplace=True)

In [14]:
sample_df.isna().sum()

Sales_Order #          0
Date                   0
Day                    0
Month                  0
Year                   0
Customer_Age           0
Age_Group              0
Customer_Gender        0
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    0
Order_Quantity         0
 Unit_Cost             0
 Unit_Price            0
 Profit                0
 Cost                  0
Revenue                0
dtype: int64

## Data Cleaning using `dropduplicates()`

In [15]:
sample_df = df.copy()

In [16]:
key_dupes = sample_df[sample_df.duplicated(subset=['Sales_Order #'], keep=False)]
key_dupes

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,2021-12-01,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,1252,2295,4172,5008,9180
1,261695,2021-12-01,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,1266,2320,1054,1266,2320
6,261701,2021-12-03,3.0,December,2021,37,Adults (35-64),M,United States,Washington,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1.0,1252,2295,1043,1252,2295
7,261701,2021-12-03,3.0,December,2021,37,Adults (35-64),M,United States,Washington,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1.0,1252,2295,1043,1252,2295

In [17]:
sample_df = sample_df.drop_duplicates(subset=['Sales_Order #'], keep='first')

In [18]:
key_dupes = sample_df[sample_df.duplicated(subset=['Sales_Order #'], keep=False)]
key_dupes

Empty DataFrame
Columns: [Sales_Order #, Date, Day, Month, Year, Customer_Age, Age_Group, Customer_Gender, Country, State, Product_Category, Sub_Category, Product_Description, Order_Quantity,  Unit_Cost ,  Unit_Price ,  Profit ,  Cost , Revenue]
Index: []

# End